ims/core/urls.py
from django.urls import path
from core.views import (
    StockItemListView, 
    OrderStockItemView, 
    OrderDetailView,
    OrderListView,
    OrderModifyView,
    OrderStockItemDeleteView,
    DashboardView
)

urlpatterns = [
    path('stockitem_list', StockItemListView.as_view(), name="stockitem_list"),
    path(
        'order/create', 
        OrderStockItemView.as_view(), 
        name="create_order"
    ),
    path('order/<str:pk>', OrderDetailView.as_view(), name='view_order'),
    path('order_list/', OrderListView.as_view(), name='order_list'),
    path(
        'order/<str:pk>/modify', 
        OrderModifyView.as_view(), 
        name="modify_order"
    ),
    path(
        'orderstockitem/<str:pk>/delete', 
        OrderStockItemDeleteView.as_view(), 
        name="delete_orderstockitem"
    ),
    path(
        'dashboard/', 
        DashboardView.as_view(), 
        name="dashboard"
    )
]

ims/ims/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import HomepageView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomepageView.as_view()),
    path('login/',LoginView.as_view(template_name="common/login.html")),
    path('logout/', LogoutView.as_view()),
    path("core/", include(("core.urls", "core"), namespace="core"))
]

urlpatterns += staticfiles_urlpatterns()

ims/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from core.constants import OrderStatus, TransactionStatus, TransactionMode

# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = "group"  


class SubGroup(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.group} | {self.name}"

    class Meta:
        db_table = "subgroup"  


class StockItem(models.Model):
    subgroup = models.ForeignKey(SubGroup, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.subgroup} | {self.name}"

    class Meta:
        db_table = "stockitem"  


class Inventory(models.Model):
    stockitem = models.ForeignKey(StockItem, on_delete=models.CASCADE, related_name="inventory")
    quantity = models.IntegerField()

    @property
    def remaining_quantity(self):
        ordered_items = OrderStockItem.objects.exclude(
            Q(order__status=OrderStatus.INVALID) | Q(is_deleted=True)
        ).filter(stockitem=self.stockitem).values_list("quantity", flat=True)
        used_quantity = sum(list(ordered_items))
        return self.quantity - used_quantity
    
    def __str__(self) -> str:
        return f"{self.stockitem} -> {self.quantity}"

    class Meta:
        db_table = "inventory"  


class Order(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(StockItem, through="OrderStockItem")
    amount = models.IntegerField()
    change_amount = models.IntegerField(default=0)
    total_order_value = models.IntegerField()
    status = models.CharField(
        max_length=255,
        choices=OrderStatus.choices, 
    )
    mode_of_payment = models.CharField(
        max_length=255,
        choices=TransactionMode.choices
    )
    customer_name = models.CharField(max_length=100, null=True, blank=True)
    customer_number = models.CharField(max_length=10, null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.id} | {self.status} | {self.customer_name} | {self.customer_number}"

    def calculate_amount(self):
        total_amount = 0
        order_stock_items = OrderStockItem.objects.exclude(is_deleted=True).filter(order=self)
        for obj in order_stock_items:
            total_amount += (obj.stockitem.price * obj.quantity)
        
        return total_amount

    class Meta:
        db_table = "order"  


class OrderStockItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    stockitem = models.ForeignKey(StockItem, on_delete=models.CASCADE)
    quantity = models.IntegerField() 
    is_deleted = models.BooleanField(default=False)

ims/core/forms.py
from django import forms
from core.models import OrderStockItem, Order
from core.constants import TransactionMode


class OrderStockItemForm(forms.Form):
    customer_name = forms.CharField(max_length=100)
    customer_number = forms.CharField(max_length=10)
    mode_of_payment = forms.ChoiceField(choices=TransactionMode, initial=TransactionMode.UPI)
    remarks = forms.Textarea()
    amount = forms.IntegerField()
    


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"

ims/core/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, UpdateView, DeleteView
from core.models import StockItem, Order, OrderStockItem, Inventory
from core.constants import TransactionMode, OrderStatus
from django.shortcuts import redirect
from django_filters.views import FilterView
from core.filters import OrderFilter, StockItemFilter
from core.forms import OrderForm
from django.contrib.auth.mixins import LoginRequiredMixin
import json
from collections import Counter

# Create your views here.


class StockItemListView(LoginRequiredMixin, FilterView):
    model = StockItem
    template_name = "core/stockitem_list.html"
    filterset_class = StockItemFilter


class OrderStockItemView(LoginRequiredMixin, TemplateView):
    template_name = "core/create_order.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["payment_options"] = list(TransactionMode._value2member_map_.keys())
        context["status_options"] = list(OrderStatus._value2member_map_.keys())
        context["stockitem_list"] = StockItem.objects.all()
        return context
    
    def post(self, request, *args, **kwargs):
        print(request.POST)
        selected_items = json.loads(request.POST["selected_items"])
        
        purchased_stockitems = []
        for key, value in selected_items.items():
            stockitem_id = int(key)
            quantity = value["quantity"]
            purchased_stockitems.append({
                    stockitem_id: quantity
                })
        
        order_data_columns = [
            "customer_name", 
            "customer_number", 
            "mode_of_payment", 
            "amount",
            "change_amount",
            "total_order_value", 
            "remarks", 
            "status"
        ]
        order_data = {
            column: request.POST[column] for column in order_data_columns
        }
        order_data["created_by"] = request.user
        order_obj = Order.objects.create(**order_data)
        for purchased_stockitem in purchased_stockitems:
            for stockitem_id, quantity in purchased_stockitem.items():
                stockitem_obj = StockItem.objects.get(id=stockitem_id)
                OrderStockItem.objects.create(**{
                    "stockitem": stockitem_obj,
                    "order": order_obj,
                    "quantity": quantity
                })    
        return redirect('core:view_order', pk=order_obj.id)
    

class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_order_valid"] = context["order"].status != OrderStatus.INVALID
        context["orderstockitem_list"] = OrderStockItem.objects.exclude(is_deleted=True).filter(order=context["order"])
        return context
    


class OrderListView(LoginRequiredMixin, FilterView):
    model = Order
    template_name = "core/order_list_v2.html"
    filterset_class = OrderFilter
    ordering = ["-created_on"]


class OrderModifyView(LoginRequiredMixin, TemplateView):
    template_name = "core/edit_order.html"

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        order_obj = Order.objects.get(id=context["pk"])
        context["order"] = order_obj
        context["payment_options"] = list(TransactionMode._value2member_map_.keys())
        context["status_options"] = list(OrderStatus._value2member_map_.keys())
        context["orderstockitem_list"] = OrderStockItem.objects.exclude(is_deleted=True).filter(order=order_obj)
        return context

    def post(self, request, *args, **kwargs):
        print(request.POST)
        purchased_stockitems = []
        for key, value in request.POST.items():
            if "purchase_quantity_" in key and value:
                stockitem_id = key.split("purchase_quantity_")[-1]
                purchased_stockitems.append({
                    stockitem_id: value
                })

        for purchased_stockitem in purchased_stockitems:
            for stockitem_id, quantity in purchased_stockitem.items():
                orderstockitem_obj = OrderStockItem.objects.get(id=stockitem_id)
                orderstockitem_obj.quantity = quantity
                orderstockitem_obj.save()    

        order_data_columns = ["customer_name", "customer_number", "mode_of_payment", "remarks", "status", "amount", "change_amount", "total_order_value"]
        order_data = {
            column: request.POST[column] for column in order_data_columns
        }
        order_data["created_by"] = request.user
        Order.objects.filter(pk=kwargs["pk"]).update(**order_data) 
           
        return redirect('core:view_order', pk=kwargs["pk"])


class OrderStockItemDeleteView(View):
    model = OrderStockItem
    
    def get(self, request, *args, **kwargs):
        orderstockitem_obj = OrderStockItem.objects.get(id=kwargs['pk'])
        orderstockitem_obj.is_deleted = True
        orderstockitem_obj.save()

        orderstockitem_obj.order.amount = orderstockitem_obj.order.calculate_amount()
        orderstockitem_obj.order.total_order_value = orderstockitem_obj.order.amount + orderstockitem_obj.order.change_amount
        orderstockitem_obj.order.save()
        return redirect('core:view_order', orderstockitem_obj.order.id)
    


class DashboardView(TemplateView):
    template_name = "core/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        completed_orders = Order.objects.filter(status=OrderStatus.COMPLETED)
        total_sales_done = sum(list(completed_orders.values_list("total_order_value", flat=True)))
        pending_orders = Order.objects.filter(status=OrderStatus.PENDING).count()

        out_of_stock_items = []
        for item in Inventory.objects.all():
            if item.remaining_quantity <= 0:
                out_of_stock_items.append({
                    "name": f"{item.stockitem.subgroup.group.name} | {item.stockitem.subgroup.name} | {item.stockitem.name}"
                })

        transaction_breakup = []
        total_order_count = completed_orders.count()
        order_category = completed_orders.values_list("mode_of_payment", flat=True)
        for mode, count in Counter(order_category).items():
            transaction_breakup.append({
                "name": mode,
                "transaction_count": count,
                "transaction_percentage": round((count/total_order_count) * 100)
            })

        context["total_completed_orders"] = completed_orders.count()
        context["total_sales_done"] = total_sales_done
        context["pending_orders"] = pending_orders
        context["out_of_stock_items"] = len(out_of_stock_items)
        context["transaction_breakup"] = transaction_breakup
        context["out_of_stock_breakup"] = out_of_stock_items

        return context

ims/core/templates/core/dashboard.html
{% extends 'common/index.html' %}

{% load static %}


{% block main_content %}

<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <!-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> -->
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Total Completed Orders</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total_completed_orders }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Total Sales Done</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">&#8377 {{ total_sales_done }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-rupee-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Orders
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ pending_orders }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                                Out of Stock Items</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ out_of_stock_items }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">

        <div class="col-xl-6 col-lg-7">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Order Breakup</h6>
                </div>
                <div class="card-body">
                    {% for transaction in transaction_breakup %}
                    <h4 class="small font-weight-bold">{{ transaction.name }} <span
                            class="float-right">{{ transaction.transaction_percentage }}% ({{ transaction.transaction_count}})</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: {{ transaction.transaction_percentage }}%"
                            aria-valuenow="{{ transaction.transaction_percentage }}" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <!-- Pie Chart -->
        <div class="col-xl-6 col-lg-7">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-danger">Out of Stock Items</h6>
                </div>
                <div class="card-body">
                    {% for item in out_of_stock_breakup %}
                    <h4 class="small font-weight-bold">{{ item.name }} <span
                            class="float-right"> 100 %</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 100%"
                            aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

</div>

{% endblock main_content %}

{% block footer_js %}
<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
{% endblock footer_js %}

ims/core/templates/core/edit_order.html
{% extends "common/index.html" %}
{% load static %}

{% block main_content %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Modify Order</h6>
    </div>
    <div class="card-body">
        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-row">
            <div class="form-group col-md-6">
                <label for="customer_name">Customer Name</label>
                <input type="text" class="form-control" name="customer_name" id="customer_name" placeholder="Customer Name" value="{{ order.customer_name }}">
            </div>
            <div class="form-group col-md-6">
                <label for="customer_number">Customer Number</label>
                <input type="text" class="form-control" name="customer_number" id="customer_number" placeholder="Customer Number" value="{{ order.customer_number }}">
            </div>
            </div>
            <div class="form-group">
                <label for="mode_of_payment">Mode of Payment</label>
                <select class="form-control" id="mode_of_payment" name="mode_of_payment" required>
                    {% for payment_option in payment_options %}
                        <option {% if order.mode_of_payment == payment_option %} selected {% endif %}>{{ payment_option }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Stock Items List</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Group</th>
                                    <th>Subgroup</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <!-- <th>Balance Quantity</th> -->
                                    <th>Purchase Quanity</th>
                                    <th>Action</th>
                                    <th style="display: none;">Select?</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item_detail in orderstockitem_list %}
                                <tr>
                                    <td>{{ item_detail.stockitem.subgroup.group.name }}</td>
                                    <td>{{ item_detail.stockitem.subgroup.name }}</td>
                                    <td>{{ item_detail.stockitem.name }}</td>
                                    <td id="price_{{item_detail.id}}">{{ item_detail.stockitem.price }}</td>
                                    <!-- <td>{{ item_detail.stockitem.inventory.first.remaining_quantity }}</td> -->
                                    <td>
                                        <!-- <label for="purchase_quantity">Purchase Quanity</label> -->
                                        <input type="number" class="form-control" name="purchase_quantity_{{item_detail.id}}" id="purchase_quantity_{{item_detail.id}}" value="{{ item_detail.quantity }}" placeholder="Purchase Quanity">
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" href="{% url 'core:delete_orderstockitem' item_detail.id %}" role="button">Delete</a>
                                    </td>
                                    <td style="display: none;">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="is_selected_{{item_detail.id}}" id="is_selected" checked >
                                            <label class="form-check-label" for="is_selected">
                                            Select?
                                            </label>
                                    </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="amount">Amount</label>
                <input type="text" class="form-control" id="amount" name="amount" placeholder="Amount is auto calculated" value="{{ order.amount }}" readonly="readonly">
            </div>
            <div class="form-group">
                <label for="amount">Change Amount</label>
                <input type="text" class="form-control" id="change_amount" name="change_amount"  value="{{ order.change_amount }}">
            </div>
            <div class="form-group">
                <label for="amount">Total Order Value</label>
                <input type="text" class="form-control" id="total_order_value" name="total_order_value" value="{{ order.total_order_value }}" readonly="readonly">
            </div>
            <div class="form-group">
                <label for="remarks">Remarks</label>
                <input type="text" class="form-control" name="remarks" id="remarks" value="{{ order.remarks }}" placeholder="Remarks">
            </div>
            <div class="form-group">
                <label for="status">Order Status</label>
                <select class="form-control" id="status" name="status" value="{{ order.status }}" required>
                    {% for status in status_options %}
                        <option {% if order.status == status %} selected {% endif %}>{{ status }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>

{% endblock main_content %}

{% block footer_js %}

<script>

    function calculateTotalAmount(){
        var checkedBoxes = document.querySelectorAll('input[type=checkbox]:checked');
            var totalAmount = 0 
            for(let i=0;i<checkedBoxes.length;i++){
                let stockitemId =  checkedBoxes[i].name.split("is_selected_").pop()
                let priceElement = document.getElementById("price_"+stockitemId);
                let price = parseInt(priceElement.innerText)
                let quantityElement = document.getElementById("purchase_quantity_"+stockitemId);
                let quantity = quantityElement.value
                if(quantity == ""){
                    quantity = 1;
                }
                else{
                    quantity = parseInt(quantity)
                }
                totalAmount += (price*quantity)
            }
            document.getElementById("amount").value = totalAmount;
    }

    function refreshTotalOrderValue(){
        let changeAmount = document.getElementById("change_amount");
        if(changeAmount.value == ""){
            changeAmount.value = 0;
        }
        let amount = parseInt(document.getElementById("amount").value)
        document.getElementById("total_order_value").value = parseInt(changeAmount.value) + amount;
    }

    $(document).ready(function() {
    
        // Logic to calculate total amount
        $('input[type=checkbox]').change(function() {
            calculateTotalAmount()
        });

        // Update amount whenever purchase quanity changes
        $('[id^=purchase_quantity_]').change(function(){
            calculateTotalAmount();
        });

        // Update total order value when change amount changes.
        $('[id=change_amount]').change(function(){
            refreshTotalOrderValue();
        });
    });
</script>


{% endblock footer_js %}

ims/core/templates/core/order_detail.html
{% extends "common/index.html" %}
{% load static %}

{% block main_content %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Order Details</h6>
        <a class="btn btn-primary" href="{% url 'core:modify_order' order.id %}" role="button">Modify Order</a>
        <a class="btn btn-success" href="{% url 'core:create_order' %}" role="button">Add new Order</a>
    </div>
    <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="customer_name">Customer Name</label>
                    <p>{{ order.customer_name }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="customer_number">Customer Number</label>
                    <p>{{ order.customer_number }}</p>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="mode_of_payment">Mode of Payment</label>
                    <p>{{ order.mode_of_payment }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="status">Order Status</label>
                    <p {% if is_order_valid is False %} style="background-color: #FF0000;" {% endif %}>{{ order.status }}</p>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="amount">Order Amount</label>
                    <p>{{ order.amount }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="change_amount">Change Amount</label>
                    <p>{{ order.change_amount }}</p>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="total_order_value">Total Order Value</label>
                    <p>{{ order.total_order_value }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="remarks">Remarks</label>
                    <p>{{ order.remarks }}</p>
                </div>
            </div>
            <div class="form-group">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Items Purchased</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Group</th>
                                    <th>Subgroup</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Quantity brought</th>
                                    <th>Item Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item_detail in orderstockitem_list %}
                                <tr>
                                    <td>{{ item_detail.stockitem.subgroup.group.name }}</td>
                                    <td>{{ item_detail.stockitem.subgroup.name }}</td>
                                    <td>{{ item_detail.stockitem.name }}</td>
                                    <td >{{ item_detail.stockitem.price }}</td>
                                    <td>{{ item_detail.quantity }}</td>
                                    <td>{% widthratio item_detail.quantity 1 item_detail.stockitem.price %}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>
</div>

{% endblock main_content %}